name: ESlint
on: [push]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting...."
      - name: ESLint checker
      # You may pin to the exact commit or the version.
      # uses: ninosaurus/eslint-check@30ce7263e3f4b0bebc3cc06897bdf4ab8524a424
      - uses: ninosaurus/eslint-check@v5.3.1

      
